#!/bin/bash

unset PACKER_VSPHERE_VCENTER_SERVER
unset PACKER_VSPHERE_ESXI_HOST
unset PACKER_VSPHERE_VM_VERSION
unset PACKER_VSPHERE_USERNAME
unset PACKER_VSPHERE_PASSWORD
unset PACKER_VSPHERE_RESOURCE_POOL
unset PACKER_VSPHERE_DATACENTER
unset PACKER_VSPHERE_DATASTORE
unset PACKER_VSPHERE_DATASTORE_ISO
unset PACKER_VSPHERE_NETWORK

unset PACKER_VMWARE_HOST
unset PACKER_VMWARE_USERNAME
unset PACKER_VMWARE_PASSWORD
unset PACKER_VMWARE_DATASTORE
unset PACKER_VMWARE_NETWORK
unset PACKER_VMWARE_MAC
unset PACKER_VMWARE_VM_VERSION

unset GOVC_URL
unset GOVC_PASSWORD
unset GOVC_USERNAME
unset GOVC_INSECURE

#govc find -type h
# Jetbrains packer-builder-vsphere plugin.
# https://github.com/jetbrains-infra/packer-builder-vsphere
export PACKER_VSPHERE_VCENTER_SERVER='placeholder'
#export PACKER_VSPHERE_ESXI_HOST='placeholder'
export PACKER_VSPHERE_ESXI_HOST='placeholder'
export PACKER_VSPHERE_VM_VERSION='13'
export PACKER_VSPHERE_DATACENTER='placeholder'
export PACKER_VSPHERE_CLUSTER='placeholder'
export PACKER_VSPHERE_RESOURCE_POOL=''
export PACKER_VSPHERE_USERNAME='placeholder'
export PACKER_VSPHERE_PASSWORD="placeholder"
export PACKER_VSPHERE_DATASTORE='placeholder'
export PACKER_VSPHERE_DATASTORE_ISO='placeholder'
export PACKER_VSPHERE_NETWORK='placeholder'

# Network Configuration
export PACKER_VSPHERE_NETWORK_IP='placeholder'
export PACKER_VSPHERE_NETWORK_MASK='placeholder'
export PACKER_VSPHERE_NETWORK_GATEWAY='placeholder'

# Native packer
export PACKER_VMWARE_HOST=${PACKER_VSPHERE_VCENTER_SERVER}
export PACKER_VMWARE_USERNAME=${PACKER_VSPHERE_USERNAME}
export PACKER_VMWARE_PASSWORD=${PACKER_VSPHERE_PASSWORD}
export PACKER_VMWARE_DATASTORE=${PACKER_VSPHERE_DATASTORE}
export PACKER_VMWARE_NETWORK=''
export PACKER_VMWARE_MAC=''
export PACKER_VMWARE_VM_VERSION=''

export GOVC_URL="https://${PACKER_VSPHERE_VCENTER_SERVER}"
export GOVC_PASSWORD=${PACKER_VSPHERE_PASSWORD}
export GOVC_USERNAME=${PACKER_VSPHERE_USERNAME}
export GOVC_INSECURE=true
export GOVC_DATASTORE=${PACKER_VSPHERE_DATASTORE}
export GOVC_DATACENTER=${PACKER_VSPHERE_DATACENTER}

export DEFAULT_DOMAIN="example"
export DEFAULT_DNS1="8.8.8.8"
export DEFAULT_DNS2="8.8.4.4"

export SERVER_PUBLIC_IP="0.0.0.0"
export SERVER_HTTP_PORT="8080"
